# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               gkno
tagline:             'Genomic pipelines'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://gkno.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Alistair Ward
  url:               https://twitter.com/AlistairNWard
  email:             AlistairNWard@gmail.com

# Custom vars
version:             1.0.0
